# Site settings
title: hai.li
email: def@hai.li
description: > # this means to ignore newlines until "baseurl:"
  hai.li
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hai.li" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:    defims
github:   defims
codepen:  defims
# dribbble: username


# Comment
disqus_shortname: hai-li
#gitment_id: e7368ae404b1a910370d
#gitment_secret: 3c4734cc2902bd41aca6d4d1770eb5f5d33acacb
# carnival: 635
#duoshuo: haili


# Google Analytics
google_analytics: UA-93485225-1


# Build settings
markdown: kramdown
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
# markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
