# Site settings
title: hai.li
email: def@hai.li
description: > # this means to ignore newlines until "baseurl:"
  hai.li
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hai.li" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:    defims
github:   defims
codepen:  defims
# dribbble: username


# Comment
# disqus_shortname: hai-li
carnival: 635


# Google Analytics
google_analytics: UA-93485225-1


# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
# markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
